/**
 * The root layout that applies to all the routes.
 * https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required
 */
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
